spring:
  profiles:
    # 设置使用的配置文件为 random 后缀的
    active: random

# 测试中使用的作者信息
author:
  # 姓名
  name: summer
  # 年龄
  age: 18
  # 性别
  gender: man

  # Map 的测试数据
  wife[name]: lili
  wife[age]: 19

  # List 的测试数据
  books[0]: spring
  books[1]: java

  # 参数间的引用
  introduce: Name:${author.name},Age:${author.gender}

  # 测试配置的优先级
  # 在主配置文件和指定环境配置文件中同时定义相同的参数时, 主配置文件中的参数会被覆盖
  property:
    value: 123123

